[package]
name = "rustputin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.4.10", default-features = false }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
log = "0.4.0"
env_logger = "0.9.0"
tinyvec = "1.5.1"
crossbeam-channel = "0.5.1"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

[build]
rustflags = "-C target-cpu=native"
