[package]
name = "shapeshifter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tt"]
spl = []
mcts = []
tt = []
debug_tt = ["tt"]

[dependencies]
axum ="0.5.6" 
tokio = { version = "1", features = ["full"] }
tower = "0.4.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8.4"
rand_pcg = "0.3"
arrayvec = "0.7"
lazy_static = "1.4.0"
fxhash = "0.2.1"
colored = "2"

[build]
rustflags = "-C target-cpu=native"

[profile.release]
lto = "off"
codegen-units = 1
