[package]
name = "shapeshifter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tt"]
spl = []
mcts = []
tt = []
debug_tt = ["tt"]

[dependencies]
rocket = { version = "0.4.10", default-features = false }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
log = "0.4.0"
env_logger = "0.9.0"
rand = "0.8.4"
rand_pcg = "0.3.1"
arrayvec = "0.7.2"
crossbeam-channel = "0.5.1"
lazy_static = "1.4.0"
fxhash = "0.2.1"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]

[build]
rustflags = "-C target-cpu=native"

[profile.release]
lto = "off"
codegen-units = 1
